service:
  name: backtest-service
  log_level: info

kafka:
  broker: kafka:9092

  consumer:
    group_id: backtest-service
    input_completed_topic: backtest.input.completed
    candle_topic: market.candle.closed

  producer:
    marker_created_topic: backtest.marker.created
    run_completed_topic: backtest.run.completed